"""The configuration client: at startup it reads a subsystem's configuration from
webtools_anagraphics.

    GET /configuration/{subsystem} → { subsystem, …the structured document… }

THE ORIGINAL is in webtools/commons/configuration/. Each Python subsystem has a copy
generated by the deployer (webtools/configurator/deploy.sh configuration): edit here
and run the deployer again, never the copy.

This is the Python twin of `configuration_client.js` beside it, which the Node
subsystems use. Neither is generated from the other: they are two files answering
the same contract, and a change to what the configuration means is made in both.
Anagraphics uses neither — it is the one serving the configuration, and reads its
own straight from MongoDB.

No default values: a subsystem without configuration, or with a missing or wrong
field, does not start. Every reader here raises `ConfigurationError`, and whoever
starts the server prints the message and exits.

Only what is needed to **reach** the configuration comes from the environment
(webtools/configurator/bootstrap.env):

    WEBTOOLS_ANAGRAPHICS_URL            where anagraphics is
    WEBTOOLS_CONFIGURATION_TIMEOUT_MS   how long to wait for it, in milliseconds

A subsystem's own storage is not among them. Not every subsystem has one — the
analyst writes through anagraphics and workspaces and owns no database — so a
client that demanded a Mongo address would refuse to start a subsystem that is
correct. Whoever has storage reads its variables itself, with
`environment_variable` below.
"""

import os
from dataclasses import dataclass
from urllib.parse import urlsplit

import httpx


class ConfigurationError(Exception):
    """Configuration missing or wrong: the server must not start."""


@dataclass(frozen=True)
class Bootstrap:
    """What comes from the environment, checked: only what reaches the configuration."""

    anagraphics_url: str
    configuration_timeout_ms: int


def read_bootstrap() -> Bootstrap:
    timeout = _positive_int(
        "WEBTOOLS_CONFIGURATION_TIMEOUT_MS", environment_variable("WEBTOOLS_CONFIGURATION_TIMEOUT_MS")
    )
    return Bootstrap(
        anagraphics_url=environment_variable("WEBTOOLS_ANAGRAPHICS_URL").rstrip("/"),
        configuration_timeout_ms=timeout,
    )


def read_configuration(subsystem: str, bootstrap: Bootstrap) -> "Configuration":
    """The subsystem's configuration document, read from anagraphics."""
    url = f"{bootstrap.anagraphics_url}/configuration/{subsystem}"
    try:
        response = httpx.get(
            url,
            headers={"accept": "application/json"},
            timeout=bootstrap.configuration_timeout_ms / 1000,
        )
    except httpx.HTTPError as error:
        raise ConfigurationError(f"GET {url}: {type(error).__name__} {error}") from error

    try:
        document = response.json()
    except ValueError as error:
        raise ConfigurationError(
            f"GET {url}: the response is not JSON (HTTP {response.status_code})"
        ) from error
    if response.status_code != 200:
        code = document.get("error", "?") if isinstance(document, dict) else "?"
        raise ConfigurationError(f"GET {url}: HTTP {response.status_code} {code}")
    if not isinstance(document, dict):
        raise ConfigurationError(f"GET {url}: the configuration is not an object")
    return Configuration(subsystem, document)


class Configuration:
    """The document that was read, with one reader per kind of field.

    The path is dotted (`limits.retention_days`); a missing field, or one of the
    wrong type, raises `ConfigurationError` naming the path, so the message in the
    log says where to look.
    """

    def __init__(self, subsystem: str, document: dict) -> None:
        self.subsystem = subsystem
        self.document = document

    def _field(self, path: str) -> object:
        value: object = self.document
        for key in path.split("."):
            value = value.get(key) if isinstance(value, dict) else None
        if value is None:
            raise self._error(path, "missing")
        return value

    def get(self, path: str) -> object:
        """A field that may legitimately not be there.

        Returns `None` when it is absent, and does **not** raise. It is the only way
        to read an optional field, and it has to be asked for by name: everywhere else
        a missing field stops the subsystem, which is the rule, and a reader that
        quietly tolerated absence would turn every field into an optional one.
        """
        value: object = self.document
        for key in path.split("."):
            value = value.get(key) if isinstance(value, dict) else None
        return value

    def _error(self, path: str, found: str) -> ConfigurationError:
        return ConfigurationError(f"configuration of {self.subsystem}: {path} is {found}")

    def string(self, path: str) -> str:
        value = self._field(path)
        if not isinstance(value, str) or not value:
            raise self._error(path, f"not a non-empty string: {value!r}")
        return value

    def boolean(self, path: str) -> bool:
        # Read before `integer`, and with `is` rather than truthiness: in Python a
        # bool is an int, so `0`/`1` in the JSON would pass a looser check and a
        # field that was meant to be a switch would take a number.
        value = self._field(path)
        if value is not True and value is not False:
            raise self._error(path, f"not a boolean: {value!r}")
        return value

    def integer(self, path: str, minimum: int = 1) -> int:
        value = self._field(path)
        # bool is an int in Python: `true` in the JSON must not pass as 1.
        if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
            raise self._error(path, f"not an integer of at least {minimum}: {value!r}")
        return value

    def number(
        self, path: str, minimum: float = float("-inf"), maximum: float = float("inf")
    ) -> float:
        """A number that is allowed a fractional part: a threshold, a rate, a share.

        Separate from `integer` because the two are different promises, and a
        threshold read as an integer would silently refuse `0.75`.
        """
        value = self._field(path)
        # bool is an int in Python: `true` in the JSON must not pass as 1.
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise self._error(path, f"not a number: {value!r}")
        if not minimum <= value <= maximum:
            raise self._error(path, f"not a number between {minimum} and {maximum}: {value!r}")
        return float(value)

    def integer_from_zero(self, path: str) -> int:
        return self.integer(path, minimum=0)

    def port(self, path: str) -> int:
        value = self.integer(path)
        if not 1 <= value <= 65535:
            raise self._error(path, f"not a port: {value!r}")
        return value

    def string_list(self, path: str) -> list[str]:
        value = self._field(path)
        if not isinstance(value, list) or not value or not all(
            isinstance(item, str) and item for item in value
        ):
            raise self._error(path, f"not a non-empty list of strings: {value!r}")
        return list(value)

    def integer_list(self, path: str) -> list[int]:
        value = self._field(path)
        if (
            not isinstance(value, list)
            or not value
            or not all(isinstance(item, int) and not isinstance(item, bool) and item > 0 for item in value)
        ):
            raise self._error(path, f"not a non-empty list of positive integers: {value!r}")
        return list(value)

    def mapping(self, path: str) -> dict:
        """An object whose keys are not known in advance (the price table).

        An **empty** object is a legitimate answer and is returned as it is: a
        price table with nothing in it means nothing is priced, which is a state
        the code handles. Absent, on the other hand, is a missing field.
        """
        value: object = self.document
        for key in path.split("."):
            value = value.get(key) if isinstance(value, dict) else None
            if value is None:
                raise self._error(path, "missing")
        if not isinstance(value, dict):
            raise self._error(path, f"not an object: {value!r}")
        return value


def environment_variable(name: str) -> str:
    """A required environment variable, with the failure every reader here uses.

    Public because a subsystem with storage of its own reads those variables
    itself, and a second copy of this check would be a second way of failing.
    """
    value = os.environ.get(name)
    if not value:
        raise ConfigurationError(f"environment variable {name} is missing")
    return value


def _positive_int(name: str, value: str) -> int:
    try:
        number = int(value)
    except ValueError:
        raise ConfigurationError(f"{name} is not a positive integer: {value!r}") from None
    if number <= 0:
        raise ConfigurationError(f"{name} is not a positive integer: {value!r}")
    return number


def http_url(configuration: Configuration, path: str) -> str:
    """A field that ends up being called: http(s) only, and no path of its own."""
    value = configuration.string(path)
    parts = urlsplit(value)
    if parts.scheme not in ("http", "https") or not parts.netloc:
        raise ConfigurationError(
            f"configuration of {configuration.subsystem}: {path} is not an http(s) address: {value!r}"
        )
    return value.rstrip("/")
