"""Sending a measurement to webtools_metrics, from a Python subsystem.

THE ORIGINAL is in webtools/commons/metrics/. Each Python subsystem has a copy
generated by the deployer (webtools/configurator/deploy.sh metrics): edit here and
run the deployer again, never the copy.

This is the Python twin of `webtools_metrics_client.js` beside it. Neither is
generated from the other, and the JavaScript one could not be copied here in any
case: what it relies on to not wait — a promise the runtime carries on its own — has
no equivalent in a synchronous Python call. What has to survive the translation is
not the shape but the identity:

  - it does not wait. `measure(...)` returns before the request has been made.
    Nothing a client does may become slower because we are counting it;
  - it does not throw. A metrics that is down, slow, full or answering nonsense
    must not turn into an error in a page or a turn of chat. What cannot be sent is
    lost, and that is a decision, not an accident: see `contesto/06. metrics.md` §2
    — the money at the demo is not taken from these numbers, so losing one costs an
    average a little accuracy and costs nothing else;
  - it does not retry. A second request for a measurement that is already stale,
    aimed at a service that has just failed to answer, makes a struggling metrics
    worse and buys a number nobody would have missed;
  - it does not write to the log unless it was told to. If metrics breaks while
    five subsystems log every failed send, the logs fill the disk — a worse failure
    than the one being reported. `metrics.log_failures` is `false` in every seed,
    and is turned on when somebody is actually looking.

What it keeps instead is a count of its own sends and failures, which `counters()`
gives back: a subsystem can always say how much it failed to report, without
anybody having to grep anything.

**How it does not wait, here.** `measure(...)` puts the measurement on a queue and
returns; one daemon thread drains the queue and does the sending. The thread is a
daemon so that a subsystem shutting down is never held open by measurements still
in hand — the same rule as everywhere else, that nothing waits for metrics.

**Why it waits once, at the very end.** The thread that sends is a daemon, so it is
killed the moment the process ends — and a process that measured something and then
exited would throw away whatever was still in hand, silently, which is exactly what
happened the first time a script used this client. So the last thing the process does
is wait for the queue to empty, for at most as long as it was already prepared to wait
for one send. Nothing waits for metrics *while the work is happening*, which is the
rule; waiting once on the way out is not that, and without it a short-lived process
cannot measure at all.

**Why the queue has a bound.** A queue that grows without one turns a metrics
outage into the subsystem's own memory filling up: the failure being reported would
take down the thing reporting it. The bound is `metrics.pending_max` in the
subsystem's configuration, and when it is reached the measurement is dropped and
counted as a failure — which is what losing a measurement already means here.
"""

import atexit
import queue
import sys
import threading
import time

import httpx


def load_metrics(configuration) -> "Metrics":
    """The client, from the subsystem's own configuration.

    No defaults: a subsystem whose configuration has no `metrics` block does not
    start, like every other field.

    **The configuration client is imported here and not at the top of the file**, and
    the reason is anagraphics. This function is the constructor for a subsystem that
    reads its configuration from anagraphics over HTTP, which is what that client
    knows how to do; anagraphics reads its own straight from MongoDB and receives no
    copy of it, deliberately. `Metrics` below needs none of that — it takes the four
    values it uses — so the dependency belongs to this function rather than to the
    file, and a subsystem that builds the client itself is not made to carry a client
    it must never use.

    As in commons/i18n, the import is the path of the **copy** (<package>/commons/),
    which is where this file is ever run from. The deployer is what puts the two next
    to each other; the original is not runnable where it is written.
    """
    from .configuration_client import ConfigurationError, http_url

    # Where metrics is lives where every other subsystem's address lives; what we do
    # when a send fails is ours, not an information about metrics, so it lives apart.
    url = http_url(configuration, "subsystems_infos.metrics.url")
    timeout_ms = configuration.integer("subsystems_infos.metrics.timeout_ms")
    log_failures = configuration.boolean("metrics.log_failures")
    pending_max = configuration.integer("metrics.pending_max")
    # The subsystem does not name itself here: it is the name its own configuration
    # was read under, so the two cannot disagree.
    subsystem = configuration.subsystem
    if not subsystem:
        raise ConfigurationError("metrics: the configuration does not say which subsystem it is")
    return Metrics(
        url=url,
        timeout_ms=timeout_ms,
        log_failures=log_failures,
        pending_max=pending_max,
        subsystem=subsystem,
    )


class Metrics:
    def __init__(
        self,
        *,
        url: str,
        timeout_ms: int,
        log_failures: bool,
        pending_max: int,
        subsystem: str,
    ) -> None:
        self._url = f"{url}/measurements"
        self._timeout_ms = timeout_ms
        self._log_failures = log_failures
        self._subsystem = subsystem
        self._pending: queue.Queue = queue.Queue(maxsize=pending_max)
        self._sent = 0
        self._failed = 0
        # The counters are read by whoever is serving a request and written by the
        # worker: two threads, so the arithmetic is guarded.
        self._counts = threading.Lock()
        self._worker = threading.Thread(
            target=self._drain, name=f"{subsystem}-metrics", daemon=True
        )
        self._worker.start()
        atexit.register(self._finish)

    def measure(self, metric: str, **fields) -> None:
        """One measurement.

        `fields` carries only what the metric declares — the vocabulary is metrics'
        own (`GET /vocabulary`), and it refuses what it does not know rather than
        storing it: a name refused there would be a number nobody could ever read.

        Returns nothing on purpose: there is nothing to wait for and nothing to
        check. Whoever calls it writes one line and goes on.
        """
        body = {"subsystem": self._subsystem, "metric": metric, **fields}
        with self._counts:
            self._sent += 1
        try:
            self._pending.put_nowait((metric, body))
        except queue.Full:
            self._failure(metric, "the queue of pending measurements is full")

    def timer(self):
        """Milliseconds since it was called, for whoever measures a duration.

        Kept here so that every subsystem measures time the same way, and from the
        monotonic clock: a wall clock that steps back would produce a negative
        duration, which is not a slow call, it is a wrong number.
        """
        start = time.monotonic()
        return lambda: round((time.monotonic() - start) * 1000)

    def counters(self) -> dict:
        """What this subsystem sent, and what it could not send."""
        with self._counts:
            return {"sent": self._sent, "failed": self._failed}

    def _drain(self) -> None:
        client = httpx.Client(timeout=self._timeout_ms / 1000)
        while True:
            metric, body = self._pending.get()
            try:
                response = client.post(
                    self._url, json=body, headers={"accept": "application/json"}
                )
                # 4xx means this subsystem is sending something the vocabulary
                # refuses: it is our mistake, not a hiccup, and it would otherwise
                # be invisible.
                if response.status_code >= 400:
                    self._failure(metric, f"HTTP {response.status_code}")
            except Exception as error:  # noqa: BLE001
                # Everything, and on purpose. This thread is the only one draining
                # the queue: if it dies the queue fills, every later measurement is
                # dropped, and nothing says why. There is no caller to raise
                # towards — that is the whole point of the file.
                self._failure(metric, f"{type(error).__name__} {error}")
            finally:
                self._pending.task_done()

    def _finish(self) -> None:
        """Let what is in hand go out, then stop waiting.

        Bounded by the timeout the sends already use: whatever is still queued after
        that was going to be lost anyway, and a process that will not exit is worse
        than a measurement that does not arrive.
        """
        deadline = time.monotonic() + self._timeout_ms / 1000
        while self._pending.unfinished_tasks and time.monotonic() < deadline:
            time.sleep(0.02)

    def _failure(self, metric: str, reason: str) -> None:
        with self._counts:
            self._failed += 1
        if self._log_failures:
            print(
                f"[{self._subsystem}] metrics: {metric} not sent ({reason})",
                file=sys.stderr,
            )
