// The configuration client: at startup it reads a subsystem's configuration from
// webtools_anagraphics.
//
//   GET /configuration/{subsystem} → { subsystem, …the structured document… }
//
// THE ORIGINAL is in webtools/commons/configuration/. Each subsystem has a copy
// generated by the deployer (webtools/configurator/deploy.sh configuration): edit
// here and run the deployer again, never the copy.
//
// No default values: a subsystem without configuration, or with a missing or
// wrong field, does not start. `loadConfiguration` throws ConfigurationError, and
// whoever starts the server prints the message and exits.
//
// Only two things come from the environment, the ones that cannot live in the
// configuration because they are what reads it
// (webtools/configurator/bootstrap.env):
//
//   WEBTOOLS_ANAGRAPHICS_URL                 where anagraphics is
//   WEBTOOLS_CONFIGURATION_TIMEOUT_MS        how long to wait for it, in milliseconds

export class ConfigurationError extends Error {
  constructor(message) {
    super(message);
    this.name = "ConfigurationError";
  }
}

// The startup environment variables, checked. `anagraphicsUrl` is needed later
// too: it is the same address for every call to anagraphics.
export function readBootstrap() {
  const anagraphicsUrl = process.env.WEBTOOLS_ANAGRAPHICS_URL;
  const timeout = process.env.WEBTOOLS_CONFIGURATION_TIMEOUT_MS;
  if (!anagraphicsUrl) throw new ConfigurationError("environment variable WEBTOOLS_ANAGRAPHICS_URL is missing");
  if (!timeout) throw new ConfigurationError("environment variable WEBTOOLS_CONFIGURATION_TIMEOUT_MS is missing");
  const timeoutMs = Number(timeout);
  if (!Number.isInteger(timeoutMs) || timeoutMs <= 0) {
    throw new ConfigurationError(`WEBTOOLS_CONFIGURATION_TIMEOUT_MS is not a positive integer: ${timeout}`);
  }
  return { anagraphicsUrl: anagraphicsUrl.replace(/\/+$/, ""), timeoutMs };
}

// → a Configuration with the methods to read its fields. Throws ConfigurationError.
export async function loadConfiguration(subsystem) {
  const { anagraphicsUrl, timeoutMs } = readBootstrap();
  const url = `${anagraphicsUrl}/configuration/${encodeURIComponent(subsystem)}`;

  let response;
  try {
    response = await fetch(url, {
      headers: { accept: "application/json" },
      signal: AbortSignal.timeout(timeoutMs),
    });
  } catch (error) {
    throw new ConfigurationError(`GET ${url}: ${error.name} ${error.message}`);
  }

  let body;
  try {
    body = await response.json();
  } catch {
    throw new ConfigurationError(`GET ${url}: response is not JSON (HTTP ${response.status})`);
  }
  if (!response.ok) {
    throw new ConfigurationError(`GET ${url}: HTTP ${response.status} ${body?.error ?? "?"}`);
  }
  return new Configuration(subsystem, body, anagraphicsUrl);
}

// The document that was read, with one method per field type. The path is dotted
// (`subsystems_infos.sso.url`); a missing field, or one of the wrong type, throws
// ConfigurationError with the path, so the error in the log says where to look.
export class Configuration {
  constructor(subsystem, document, anagraphicsUrl) {
    this.subsystem = subsystem;
    this.document = document;
    this.anagraphicsUrl = anagraphicsUrl;
  }

  #fail(path, value, expected) {
    const found = value === undefined ? "missing" : `found ${JSON.stringify(value)}`;
    return new ConfigurationError(`configuration of ${this.subsystem}: ${path} must be ${expected}, ${found}`);
  }

  get(path) {
    let value = this.document;
    for (const key of path.split(".")) {
      value = value !== null && typeof value === "object" ? value[key] : undefined;
    }
    return value;
  }

  string(path) {
    const value = this.get(path);
    if (typeof value === "string" && value.length > 0) return value;
    throw this.#fail(path, value, "a non-empty string");
  }

  boolean(path) {
    const value = this.get(path);
    if (typeof value === "boolean") return value;
    throw this.#fail(path, value, "true or false");
  }

  integer(path, { min = Number.MIN_SAFE_INTEGER, max = Number.MAX_SAFE_INTEGER } = {}) {
    const value = this.get(path);
    if (Number.isInteger(value) && value >= min && value <= max) return value;
    throw this.#fail(path, value, `an integer between ${min} and ${max}`);
  }

  // A number with a decimal point: thresholds, probabilities, factors. Amounts do
  // **not** come through here: those are integers in cents.
  number(path, { min = -Infinity, max = Infinity } = {}) {
    const value = this.get(path);
    if (typeof value === "number" && Number.isFinite(value) && value >= min && value <= max) return value;
    throw this.#fail(path, value, `a number between ${min} and ${max}`);
  }

  port(path) {
    return this.integer(path, { min: 1, max: 65535 });
  }

  stringList(path) {
    const value = this.get(path);
    if (Array.isArray(value) && value.length > 0 && value.every((item) => typeof item === "string" && item)) {
      return value;
    }
    throw this.#fail(path, value, "a non-empty list of strings");
  }

  // Only http or https: these addresses end up in an href or in a fetch, and a
  // `javascript:` in an href is code run on click. Without the trailing slash,
  // because whoever uses them appends a path that starts with `/`.
  httpUrl(path) {
    const value = this.get(path);
    try {
      const url = new URL(value);
      if (url.protocol === "http:" || url.protocol === "https:") return value.replace(/\/+$/, "");
    } catch {
      // Falls through below: it is not an address.
    }
    throw this.#fail(path, value, "an http(s) address");
  }

  httpUrlList(path) {
    return this.stringList(path).map((_, index) => this.httpUrl(`${path}.${index}`));
  }
}
