"""The languages, for a subsystem written in Python: catalogues and translation.

THE ORIGINAL is in webtools/commons/i18n/. Each subsystem has a copy generated by the
deployer (webtools/configurator/deploy.sh i18n), together with **all** the catalogues:
edit here and run the deployer again, never the copy.

It reads the same `locales/<language>.json` the pages read — one catalogue per
language, English keys, dotted, grouped by area — because a text the client reads is
the same text wherever it is written, and a second place to keep it would be a second
place to forget.

**It is not a port of `webtools_i18n.js`, and the difference is deliberate.** That
module answers the questions a *page* asks: which language this request is in, read
from a cookie or from `Accept-Language`; how to escape a value into HTML; what the
language switcher offers; how to write an amount in euro. A **document** has none of
those — no request, no browser, no HTML — and the language it is written in is not
chosen here: it is a fact carried on the material, the language the client wrote in.
What is left is what this file has: the catalogues, a key, and the text.

    texts = load_i18n(configuration)
    words = texts.in_language("it")
    words.t("analyst.proposal.title")
    words.t("analyst.proposal.count", points=3)      # "… {points} …"
    words.has("analyst.proposal.note")

A key missing from the chosen language is taken from the fallback language. Missing
there too, the key itself comes back — immediately visible in whatever it was written
into — and it is reported once.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

# One directory up from the copy, which is where this file is ever run from: the
# deployer puts it in `<package>/commons/i18n/`, next to the catalogues, and the
# configuration client is its neighbour's neighbour. The original is not runnable
# where it is written.
from ..configuration_client import ConfigurationError

LOCALES = Path(__file__).resolve().parent / "locales"

_PLACEHOLDER = re.compile(r"\{(\w+)\}")


def _read_catalogue(locale: str) -> dict:
    file = LOCALES / f"{locale}.json"
    if not file.is_file():
        raise ConfigurationError(
            f"i18n: language {locale} is in the configuration but has no catalogue at {file}"
        )
    try:
        catalogue = json.loads(file.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise ConfigurationError(f"i18n: catalogue {locale} cannot be read: {error}") from error
    if not isinstance(catalogue, dict):
        raise ConfigurationError(f"i18n: catalogue {locale} must be a JSON object")
    return catalogue


def _lookup(catalogue: dict, key: str) -> str | None:
    value: object = catalogue
    for part in key.split("."):
        value = value.get(part) if isinstance(value, dict) else None
    return value if isinstance(value, str) else None


def _interpolate(text: str, values: dict) -> str:
    """`{name}` becomes the value. A placeholder nobody passed stays as it is: it is a
    key written with a hole in it, and showing the hole says more than hiding it."""
    if not values:
        return text
    return _PLACEHOLDER.sub(
        lambda found: str(values[found.group(1)]) if found.group(1) in values else found.group(0),
        text,
    )


@dataclass(frozen=True)
class Texts:
    """The catalogues of the languages offered, and the fallback among them."""

    locales: tuple[str, ...]
    fallback_locale: str
    catalogues: dict[str, dict]
    # Keys missing from the fallback language too are reported once, not once per
    # document written.
    _reported: set[str] = field(default_factory=set, repr=False, compare=False)

    def in_language(self, locale: str) -> "Words":
        """The catalogue to write in. The language is whatever the material said, and a
        language we have no catalogue for is not an error: the fallback answers, which
        is what a fallback is for."""
        return Words(self, locale)

    def _text(self, locale: str, key: str) -> str | None:
        found = _lookup(self.catalogues.get(locale, {}), key)
        if found is not None:
            return found
        return _lookup(self.catalogues.get(self.fallback_locale, {}), key)


@dataclass(frozen=True)
class Words:
    """One language of the catalogues, so a key is asked for on its own."""

    texts: Texts
    locale: str

    def has(self, key: str) -> bool:
        """Is there a text for this key, here or in the fallback language?"""
        return self.texts._text(self.locale, key) is not None

    def t(self, key: str, **values) -> str:
        text = self.texts._text(self.locale, key)
        if text is None:
            if key not in self.texts._reported:
                self.texts._reported.add(key)
                print(f"[i18n] key missing from {self.texts.fallback_locale} as well: {key}")
            return key
        return _interpolate(text, values)


def load_i18n(configuration) -> Texts:
    """The catalogues, from the subsystem's own configuration.

    No defaults: a subsystem whose configuration has no `i18n` block does not start,
    like every other field. Only the two fields a document needs are read — which
    languages there are, and which one answers when a key is missing. The cookie and
    the size of a form's body are a page's business and are not asked for here.
    """
    locales = configuration.string_list("i18n.locales")
    fallback_locale = configuration.string("i18n.fallback_locale")
    if fallback_locale not in locales:
        raise ConfigurationError(
            f"i18n: fallback_locale {fallback_locale} is not among the languages offered "
            f"({', '.join(locales)})"
        )
    return Texts(
        locales=tuple(locales),
        fallback_locale=fallback_locale,
        catalogues={locale: _read_catalogue(locale) for locale in locales},
    )
