// Sending a measurement to webtools_metrics.
//
// THE ORIGINAL is in webtools/commons/metrics/. Each subsystem has a copy
// generated by the deployer (webtools/configurator/deploy.sh metrics): edit here
// and run the deployer again, never the copy.
//
// The whole point of this file is what it does **not** do:
//
//   - it does not wait. `measure(...)` returns at once, before the request has
//     been made. Nothing a client does may become slower because we are counting
//     it;
//   - it does not throw. A metrics that is down, slow, full or answering
//     nonsense must not turn into an error in a page or a turn of chat. What
//     cannot be sent is lost, and that is a decision, not an accident: see
//     `contesto/06. metrics.md` §2 — the money at the demo is not taken from
//     these numbers, so losing one costs an average a little accuracy and costs
//     nothing else;
//   - it does not retry. A second request for a measurement that is already
//     stale, aimed at a service that has just failed to answer, makes a struggling
//     metrics worse and buys a number nobody would have missed;
//   - it does not write to the log unless it was told to. If metrics breaks while
//     five subsystems log every failed send, the logs fill the disk — a worse
//     failure than the one being reported. `metrics.log_failures` is `false` in
//     every seed, and is turned on when somebody is actually looking.
//
// What it keeps instead is a count of its own sends and failures, which
// `counters()` gives back: a subsystem can always say how much it failed to
// report, without anybody having to grep anything.

// As in commons/i18n: the path is the one of the **copy** (src/commons/), which
// is where this file is ever run from. The deployer is what puts the two next to
// each other; the original is not runnable where it is written.
import { ConfigurationError } from "../configuration_client.js";

// The subsystem's configuration says where metrics is and how long it may take.
// No defaults: a subsystem whose configuration has no `metrics` block does not
// start, like every other field.
export function loadMetrics(configuration) {
  // Where metrics is lives where every other subsystem's address lives; what we
  // do when a send fails is ours, not an information about metrics, so it lives
  // apart.
  const url = configuration.httpUrl("subsystems_infos.metrics.url");
  const timeoutMs = configuration.integer("subsystems_infos.metrics.timeout_ms", { min: 1 });
  const logFailures = configuration.boolean("metrics.log_failures");
  // The subsystem does not name itself here: it is the name its own
  // configuration was read under, so the two cannot disagree.
  const subsystem = configuration.subsystem;
  if (!subsystem) throw new ConfigurationError("metrics: the configuration does not say which subsystem it is");
  return new Metrics({ url, timeoutMs, logFailures, subsystem });
}

export class Metrics {
  #url;
  #timeoutMs;
  #logFailures;
  #subsystem;
  #sent = 0;
  #failed = 0;

  constructor({ url, timeoutMs, logFailures, subsystem }) {
    this.#url = `${url}/measurements`;
    this.#timeoutMs = timeoutMs;
    this.#logFailures = logFailures;
    this.#subsystem = subsystem;
  }

  // One measurement. `fields` carries only what the metric declares — the
  // vocabulary is metrics' own (GET /vocabulary), and it refuses what it does not
  // know rather than storing it: a name refused here would be a number nobody
  // could ever read.
  //
  // Returns nothing on purpose: there is nothing to wait for and nothing to
  // check. Whoever calls it writes one line and goes on.
  measure(metric, fields = {}) {
    const body = JSON.stringify({ subsystem: this.#subsystem, metric, ...fields });
    this.#sent += 1;
    // No `await`, and the rejection is handled here: an unhandled rejection in a
    // measurement would take down the process it was measuring.
    fetch(this.#url, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body,
      signal: AbortSignal.timeout(this.#timeoutMs),
    })
      .then((response) => {
        // 4xx means this subsystem is sending something the vocabulary refuses:
        // it is our mistake, not a hiccup, and it would otherwise be invisible.
        if (!response.ok) this.#failure(metric, `HTTP ${response.status}`);
      })
      .catch((error) => this.#failure(metric, `${error.name} ${error.message}`));
  }

  // Milliseconds since it was called, for whoever measures a duration. Kept here
  // so that every subsystem measures time the same way, and from the monotonic
  // clock: a wall clock that steps back would produce a negative duration, which
  // is not a slow call, it is a wrong number.
  timer() {
    const start = performance.now();
    return () => Math.round(performance.now() - start);
  }

  // What this subsystem sent, and what it could not send. Read by whoever wants
  // to know how much of its own reporting is missing.
  counters() {
    return { sent: this.#sent, failed: this.#failed };
  }

  #failure(metric, reason) {
    this.#failed += 1;
    if (this.#logFailures) {
      console.warn(`[${this.#subsystem}] metrics: ${metric} not sent (${reason})`);
    }
  }
}
